# Generated by Django

from django.db import migrations, models


def default_user_settings() -> dict:
    # Inlined from the old apps.users.models; the field is removed in 0003.
    return {"theme_colors": {}, "default_view": "all"}


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="settings",
            field=models.JSONField(
                blank=True,
                default=default_user_settings,
                help_text="User UI/UX preferences and encrypted per-user credentials.",
            ),
        ),
    ]
