# Generated by Django 5.2.17 on 2026-10-03 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_settings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="user",
            name="settings",
        ),
    ]
