# Generated by Django 5.2.17 on 2026-10-04 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_organization_remove_user_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="passkey_required",
            field=models.BooleanField(
                default=False,
                help_text="Sign-in needs a passkey after the password. With none saved, the next sign-in sets one up.",
            ),
        ),
        migrations.CreateModel(
            name="Passkey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                (
                    "credential_id",
                    models.CharField(
                        help_text="base64url", max_length=512, unique=True
                    ),
                ),
                ("public_key", models.BinaryField()),
                ("sign_count", models.PositiveBigIntegerField(default=0)),
                ("transports", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passkeys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
