# Generated by Django 5.2.17 on 2026-10-04 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "items",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Product key -> cubic yards.",
                    ),
                ),
                ("loads", models.JSONField(blank=True, default=list)),
                ("charge_rush_fee", models.BooleanField(default=False)),
                ("priced", models.JSONField(blank=True, default=dict)),
                (
                    "note",
                    models.TextField(blank=True, help_text="Shown to the customer."),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=9),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Yard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="Matches the yard keys in data/service_area.json.",
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("address", models.CharField(blank=True, max_length=255)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Inactive yards are never routed to."
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("service", "Service"),
                            ("fee", "Fee"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=16,
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=6),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="intake.invoice",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("delivery", "Delivery"),
                            ("callback", "Contact me / special request"),
                        ],
                        default="delivery",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("scheduled", "Scheduled"),
                            ("delivered", "Delivered"),
                            ("declined", "Declined"),
                        ],
                        default="new",
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("delivery_address", models.CharField(blank=True, max_length=255)),
                ("zip_code", models.CharField(blank=True, db_index=True, max_length=5)),
                (
                    "items",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Product key -> cubic yards.",
                    ),
                ),
                ("preferred_date", models.DateField(blank=True, null=True)),
                (
                    "delivery_window",
                    models.CharField(
                        choices=[
                            ("any", "Any time"),
                            ("morning", "Morning"),
                            ("afternoon", "Afternoon"),
                        ],
                        default="any",
                        max_length=12,
                    ),
                ),
                (
                    "placement_notes",
                    models.TextField(
                        blank=True, help_text="Where to dump it, access, gate codes..."
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("language", models.CharField(default="en", max_length=8)),
                ("quote", models.JSONField(blank=True, default=dict)),
                (
                    "estimated_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=9, null=True
                    ),
                ),
                ("is_rush", models.BooleanField(default=False)),
                (
                    "coverage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("serve", "In our area"),
                            ("contact", "Special request area"),
                            ("outside", "Outside our area"),
                            ("", "No zip given"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "plan_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Not planned"),
                            ("ok", "Routed"),
                            ("no_capacity", "No truck available"),
                            ("out_of_stock", "Out of stock"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("scheduled_date", models.DateField(blank=True, null=True)),
                ("delivered_on", models.DateField(blank=True, null=True)),
                (
                    "final_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=9, null=True
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True, help_text="Private; never shown to the customer."
                    ),
                ),
                ("contact_consent", models.BooleanField(default=False)),
                ("marketing_consent", models.BooleanField(default=False)),
                ("consent_version", models.CharField(blank=True, max_length=20)),
                ("consent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "claim_token_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice",
                to="intake.order",
            ),
        ),
        migrations.CreateModel(
            name="OrderMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_staff", models.BooleanField(default=False)),
                ("body", models.TextField(max_length=4000)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="intake.order",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Truck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="e.g. Truck 3 (tandem)", max_length=60),
                ),
                (
                    "capacity_yards",
                    models.PositiveSmallIntegerField(help_text="Cubic yards per load."),
                ),
                (
                    "workday_minutes",
                    models.PositiveSmallIntegerField(
                        default=600,
                        help_text="Driving + loading time available per day.",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Off = in the shop / not in service."
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "yard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trucks",
                        to="intake.yard",
                    ),
                ),
            ],
            options={
                "ordering": ["yard__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="OrderLoad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.CharField(
                        choices=[
                            ("screened_topsoil", "Screened topsoil"),
                            ("garden_blend", "Garden blend"),
                            ("compost", "Compost"),
                            ("fill_dirt", "Fill dirt"),
                            ("washed_sand", "Washed sand"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(help_text="Cubic yards."),
                ),
                ("date", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "miles",
                    models.DecimalField(decimal_places=1, default=0, max_digits=6),
                ),
                (
                    "minutes",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Truck time: loading, round trip, dumping."
                    ),
                ),
                ("sequence", models.PositiveSmallIntegerField(default=0)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loads",
                        to="intake.order",
                    ),
                ),
                (
                    "truck",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loads",
                        to="intake.truck",
                    ),
                ),
                (
                    "yard",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loads",
                        to="intake.yard",
                    ),
                ),
            ],
            options={
                "ordering": ["order_id", "sequence", "id"],
            },
        ),
        migrations.CreateModel(
            name="TruckDayOff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("reason", models.CharField(blank=True, max_length=120)),
                (
                    "truck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days_off",
                        to="intake.truck",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("truck", "date"), name="unique_truck_day_off"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="YardStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.CharField(
                        choices=[
                            ("screened_topsoil", "Screened topsoil"),
                            ("garden_blend", "Garden blend"),
                            ("compost", "Compost"),
                            ("fill_dirt", "Fill dirt"),
                            ("washed_sand", "Washed sand"),
                        ],
                        max_length=32,
                    ),
                ),
                ("in_stock", models.BooleanField(default=True)),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Restock expected Friday",
                        max_length=120,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "yard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock",
                        to="intake.yard",
                    ),
                ),
            ],
            options={
                "ordering": ["yard__name", "product"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("yard", "product"), name="unique_stock_per_yard_product"
                    )
                ],
            },
        ),
    ]
