# Generated by Django 5.2.17 on 2026-10-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[("booking", "Booking"), ("callback", "Contact me")],
                        default="booking",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("declined", "Declined"),
                        ],
                        default="new",
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("service_address", models.CharField(blank=True, max_length=255)),
                ("vin", models.CharField(blank=True, max_length=17)),
                ("vehicle_year", models.CharField(blank=True, max_length=4)),
                ("vehicle_make", models.CharField(blank=True, max_length=60)),
                ("vehicle_model", models.CharField(blank=True, max_length=60)),
                (
                    "services",
                    models.JSONField(
                        blank=True, default=dict, help_text="Service key -> quantity."
                    ),
                ),
                ("other_description", models.TextField(blank=True)),
                ("preferred_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("estimate", models.JSONField(blank=True, default=dict)),
                (
                    "estimated_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("is_emergency", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
