# Generated by Django 5.2.17 on 2026-10-02 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[("booking", "Booking"), ("callback", "Contact me")],
                        default="booking",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("declined", "Declined"),
                        ],
                        default="new",
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("service_address", models.CharField(blank=True, max_length=255)),
                ("vin", models.CharField(blank=True, max_length=17)),
                ("vehicle_year", models.CharField(blank=True, max_length=4)),
                ("vehicle_make", models.CharField(blank=True, max_length=60)),
                ("vehicle_model", models.CharField(blank=True, max_length=60)),
                (
                    "services",
                    models.JSONField(
                        blank=True, default=dict, help_text="Service key -> quantity."
                    ),
                ),
                ("other_description", models.TextField(blank=True)),
                ("preferred_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("estimate", models.JSONField(blank=True, default=dict)),
                (
                    "estimated_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("is_emergency", models.BooleanField(default=False)),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("completed_on", models.DateField(blank=True, null=True)),
                ("odometer", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "final_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True, help_text="Private; never shown to the customer."
                    ),
                ),
                (
                    "claim_token_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RequestMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_staff", models.BooleanField(default=False)),
                ("body", models.TextField(max_length=4000)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="intake.servicerequest",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vin", models.CharField(max_length=17)),
                ("year", models.CharField(blank=True, max_length=4)),
                ("make", models.CharField(blank=True, max_length=60)),
                ("model", models.CharField(blank=True, max_length=60)),
                ("nickname", models.CharField(blank=True, max_length=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_requests",
                to="intake.vehicle",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.UniqueConstraint(
                fields=("owner", "vin"), name="unique_vehicle_per_owner"
            ),
        ),
    ]
