# Generated by Django 5.2.17 on 2026-10-03 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="parts_estimate_result",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="parts_estimate_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not requested"),
                    ("pending", "Pending"),
                    ("ready", "Ready"),
                    ("unavailable", "Unavailable"),
                ],
                default="",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="vehicle_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sedan", "Sedan / car"),
                    ("crossover", "Crossover"),
                    ("suv", "SUV / van"),
                    ("truck", "Truck"),
                    ("european", "European"),
                ],
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="PartPriceExample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("brake_pads", "Brake pads"),
                            ("brake_rotors", "Brake rotors"),
                            ("suspension", "Suspension (struts / shocks)"),
                            ("oil_change", "Oil change"),
                            ("spark_plugs", "Spark plugs"),
                            ("alternator", "Alternator"),
                            ("belt_replacement", "Belt replacement (serpentine)"),
                            ("air_filter", "Air filter"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("sedan", "Sedan / car"),
                            ("crossover", "Crossover"),
                            ("suv", "SUV / van"),
                            ("truck", "Truck"),
                            ("european", "European"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "vehicle_make",
                    models.CharField(
                        blank=True,
                        help_text="Optional, e.g. TOYOTA. Blank = any make of this type.",
                        max_length=40,
                    ),
                ),
                (
                    "part_brand",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Duralast Gold, Akebono",
                        max_length=60,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Ceramic pads, 2018 Camry front",
                        max_length=120,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, help_text="e.g. AutoZone, RockAuto", max_length=40
                    ),
                ),
                ("source_url", models.URLField(blank=True, max_length=500)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["service", "vehicle_type", "vehicle_make", "price"],
                "indexes": [
                    models.Index(
                        fields=["service", "vehicle_type"],
                        name="intake_part_service_7e8dde_idx",
                    )
                ],
            },
        ),
    ]
