# Generated by Django 5.2.17 on 2026-10-03 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartsEstimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("vehicle", models.JSONField(default=dict)),
                ("services", models.JSONField(default=dict)),
                ("result", models.JSONField(default=dict)),
                ("model_name", models.CharField(blank=True, max_length=64)),
                ("generated_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="parts_estimate_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not requested"),
                    ("pending", "Pending"),
                    ("ready", "Ready"),
                    ("unavailable", "Unavailable"),
                ],
                default="",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="parts_estimate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="intake.partsestimate",
            ),
        ),
    ]
