# Generated by Django 5.2.17 on 2026-10-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0002_parts_estimates"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="language",
            field=models.CharField(default="en", max_length=8),
        ),
    ]
