# Generated by Django 6.1.1 on 2026-10-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0003_request_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partpriceexample',
            name='service',
            field=models.CharField(choices=[('brake_pads', 'Brake pads'), ('brake_rotors', 'Brake rotors'), ('suspension', 'Suspension (struts / shocks)'), ('oil_change', 'Oil & filter change'), ('spark_plugs', 'Spark plugs'), ('alternator', 'Alternator'), ('belt_replacement', 'Belt replacement (serpentine)'), ('air_filter', 'Air filter')], max_length=32),
        ),
    ]
