# Generated by Django 5.2.17 on 2026-10-03 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0004_alter_partpriceexample_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "services",
                    models.JSONField(
                        blank=True, default=dict, help_text="Service key -> quantity."
                    ),
                ),
                ("charge_rush_fee", models.BooleanField(default=False)),
                ("labor", models.JSONField(blank=True, default=dict)),
                (
                    "note",
                    models.TextField(blank=True, help_text="Shown to the customer."),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=9),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice",
                        to="intake.servicerequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("part", "Part"),
                            ("shipping", "Shipping"),
                            ("labor", "Extra labor"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=16,
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=6),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="intake.invoice",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
    ]
