# Generated by Django 5.2.17 on 2026-10-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0005_invoices"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="consent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="consent_version",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="contact_consent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="marketing_consent",
            field=models.BooleanField(default=False),
        ),
    ]
