# Generated by Django 5.2.17 on 2026-10-03 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("users", "0003_remove_user_organization_remove_user_settings"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Organization",
        ),
    ]
